# Generated by Django 3.2.7 on 2021-09-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-id',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
