# Generated by Django 3.2 on 2021-08-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='products', verbose_name='image'),
        ),
    ]
