# Generated by Django 3.2 on 2021-09-08 05:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(null=True, verbose_name='price'),
        ),
    ]
