# Generated by Django 3.2.7 on 2021-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210908_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='discount'),
        ),
    ]
